// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"micro-project-mall/user/rpc/internal/logic"
	"micro-project-mall/user/rpc/internal/svc"
	"micro-project-mall/user/rpc/types/rpc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *rpc.IdRequest) (*rpc.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
